<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            [
                'products_id' => 1,
                'product_images_url' => 'img/1.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 1,
                'product_images_url' => 'img/1.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 2,
                'product_images_url' => 'img/2.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 2,
                'product_images_url' => 'img/2.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 3,
                'product_images_url' => 'img/3.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 4,
                'product_images_url' => 'img/4.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 5,
                'product_images_url' => 'img/5.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 6,
                'product_images_url' => 'img/6.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 7,
                'product_images_url' => 'img/7.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 8,
                'product_images_url' => 'img/8.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 9,
                'product_images_url' => 'img/9.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 10,
                'product_images_url' => 'img/10.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 10,
                'product_images_url' => 'img/10.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 11,
                'product_images_url' => 'img/11.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 11,
                'product_images_url' => 'img/11.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 12,
                'product_images_url' => 'img/12.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 13,
                'product_images_url' => 'img/13.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 14,
                'product_images_url' => 'img/14.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 15,
                'product_images_url' => 'img/15.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 16,
                'product_images_url' => 'img/16.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 17,
                'product_images_url' => 'img/17.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 18,
                'product_images_url' => 'img/18.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 19,
                'product_images_url' => 'img/19.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 20,
                'product_images_url' => 'img/20.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 21,
                'product_images_url' => 'img/21.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 22,
                'product_images_url' => 'img/22.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 22,
                'product_images_url' => 'img/22.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 23,
                'product_images_url' => 'img/23.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 24,
                'product_images_url' => 'img/24.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 24,
                'product_images_url' => 'img/24.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 25,
                'product_images_url' => 'img/25.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 26,
                'product_images_url' => 'img/26.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 27,
                'product_images_url' => 'img/27.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 28,
                'product_images_url' => 'img/28.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 29,
                'product_images_url' => 'img/29.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 30,
                'product_images_url' => 'img/30.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 31,
                'product_images_url' => 'img/31.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 32,
                'product_images_url' => 'img/32.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 33,
                'product_images_url' => 'img/33.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 34,
                'product_images_url' => 'img/34.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 34,
                'product_images_url' => 'img/34.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 35,
                'product_images_url' => 'img/35.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 35,
                'product_images_url' => 'img/35.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 35,
                'product_images_url' => 'img/35.3.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 36,
                'product_images_url' => 'img/36.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 37,
                'product_images_url' => 'img/37.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 38,
                'product_images_url' => 'img/38.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 39,
                'product_images_url' => 'img/39.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 40,
                'product_images_url' => 'img/40.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 41,
                'product_images_url' => 'img/41.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 41,
                'product_images_url' => 'img/41.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 42,
                'product_images_url' => 'img/42.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 43,
                'product_images_url' => 'img/43.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 44,
                'product_images_url' => 'img/44.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 45,
                'product_images_url' => 'img/45.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 45,
                'product_images_url' => 'img/45.2.jpg',
                'product_images_is_primary' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 46,
                'product_images_url' => 'img/46.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 47,
                'product_images_url' => 'img/47.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 48,
                'product_images_url' => 'img/48.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 49,
                'product_images_url' => 'img/49.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_id' => 50,
                'product_images_url' => 'img/50.1.jpg',
                'product_images_is_primary' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];


        DB::table('product_images')->insert($data);
        
    }
}
