<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('products')->insert([
            // ACADEMIC
            [
                'products_title' => 'Sapiens: A Brief History of Humankind',
                'products_author_name' => 'Yuval Noah Harari',
                'products_publisher_name' => 'Penguin Random House',
                'products_published_year' => '2011',
                'products_price' => '900000',
                'products_stock' => '5',
                'products_summary' => 'Buku ini menelusuri sejarah manusia dari munculnya Homo sapiens hingga era modern, menjelaskan bagaimana manusia menjadi spesies dominan di Bumi. Harari mengeksplorasi revolusi kognitif, pertanian, dan ilmiah yang membentuk peradaban kita saat ini.',
                'products_isbn' => '978-0062316097',
                'products_total_pages' => '500 halaman',
                'products_languange' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Thinking, Fast and Slow',
                'products_author_name' => 'Daniel Kahneman',
                'products_publisher_name' => 'Farrar, Straus and Giroux',
                'products_published_year' => '2011',
                'products_price' => '400000',
                'products_stock' => '8',
                'products_summary' => 'Kahneman memperkenalkan dua sistem pemikiran yang mempengaruhi keputusan kita: Sistem 1 yang cepat dan intuitif, serta Sistem 2 yang lambat dan analitis. Buku ini mengungkap berbagai bias kognitif yang seringkali memengaruhi penalaran dan pengambilan keputusan kita sehari-hari.',
                'products_isbn' => '9786020637181',
                'products_total_pages' => '499 halaman',
                'products_languange' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Metodologi Penelitian Kualitatif',
                'products_author_name' => 'Lexy J. Moleong',
                'products_publisher_name' => 'Remadja Karya',
                'products_published_year' => '1989',
                'products_price' => '182000',
                'products_stock' => '3',
                'products_summary' => 'Buku ini menjadi panduan fundamental bagi peneliti yang ingin mendalami pendekatan kualitatif dalam riset. Moleong menjelaskan berbagai teknik pengumpulan dan analisis data kualitatif, menekankan pentingnya pemahaman mendalam terhadap fenomena yang diteliti.',
                'products_isbn' => '9795140515',
                'products_total_pages' => '253 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Statistika untuk Penelitian',
                'products_author_name' => 'Dr. Sumanto, MA',
                'products_publisher_name' => 'Penerbit Andi',
                'products_published_year' => '2024',
                'products_price' => '98000',
                'products_stock' => '10',
                'products_summary' => 'Buku ini berusaha untuk menggabungkan keduanya dalam satu paket agar para mahasiswa mendapatkan pemahaman secara utuh dari pembahasan yang tidak terpisah-pisah; satu analisis (yang dibutuhkan) didapat dalam satu pembahasan dan dalam satu buku saja.',
                'products_isbn' => '9786230142017',
                'products_total_pages' => '304 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Komunikasi Politik : Teori, Strategi, dan Penerapannya di Era Kontemporer',
                'products_author_name' => 'Dewi Indra Puspitasari',
                'products_publisher_name' => 'Anak Hebat Indonesia',
                'products_published_year' => '2025',
                'products_price' => '85000',
                'products_stock' => '5',
                'products_summary' => 'Buku bertajuk Komunikasi Politik ini mengupas peran penting komunikasi politik dalam era digital yang semakin terhubung. Buku ini menawarkan pemahaman komprehensif tentang bagaimana strategi komunikasi politik dapat membentuk opini publik dan memengaruhi keputusan politik.',
                'products_isbn' => '9786235153469',
                'products_total_pages' => '422 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'The Origin of Species',
                'products_author_name' => 'Charles Darwin',
                'products_publisher_name' => 'Narasi',
                'products_published_year' => '2017',
                'products_price' => '250000',
                'products_stock' => '5',
                'products_summary' => 'Darwin menyajikan teori evolusi melalui seleksi alam, menjelaskan bagaimana spesies berkembang dan beradaptasi seiring waktu. Karyanya merevolusi pemahaman ilmiah tentang keanekaragaman hayati dan asal-usul kehidupan di Bumi.',
                'products_isbn' => '9789791685276',
                'products_total_pages' => '596 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Project PHP: Membangun Sistem Informasi Akademik Dengan Framework Codeigniter',
                'products_author_name' => 'Badiyanto',
                'products_publisher_name' => 'Langit Inspirasi',
                'products_published_year' => '2018',
                'products_price' => '250000',
                'products_stock' => '7',
                'products_summary' => 'Buku ini membahas tentang bagaimana konsep dasar pemrograman web dengan Framework Codeigniter secara mudah dan cepat yang dikemas dengan bahasa yang mudah dimengerti dan di dukung dengan gambar, selain itu juga membahas bagaimana membuat Project PHP.',
                'products_isbn' => '9786027117747',
                'products_total_pages' => '476 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ART & PHOTOGRAPHY
            [
                'products_title' => 'Instaxnesia: A Nation of Creative Expression',
                'products_author_name' => 'Fujifilm Indonesia',
                'products_publisher_name' => 'Kepustakaan Populer Gramedia',
                'products_published_year' => '2025',
                'products_price' => '220000',
                'products_stock' => '5',
                'products_summary' => 'Koleksi foto ini menangkap beragam cerita kreatif dari para kreator Indonesia, menggunakan keajaiban kamera instan yang mampu mengabadikan momen dengan cepat. Tak hanya itu, di dalamnya pun terdapat upaya eksperimen untuk mengeksplorasi pesona kreatif Indonesia yang unik melalui fotografi instan.',
                'products_isbn' => '9786231342911',
                'products_total_pages' => '200 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Art Girl Setsuko Negishi dan Kawan-Kawannya',
                'products_author_name' => 'Mitsuru Hanagata',
                'products_publisher_name' => 'm&c!',
                'products_published_year' => '2022',
                'products_price' => '75000',
                'products_stock' => '9',
                'products_summary' => 'Setsuko Negishi adalah ketua dari klub kesenian yang keberadaannya sedang di ambang bahaya. Sebenarnya saat ia masih kelas 1, klub seni adalah klub yang anggotanya sangat sering mendapatkan prestasi. Tapi kemudian tidak ada lagi anak kelas 2 yang bergabung dengan klub.',
                'products_isbn' => '9786230305986',
                'products_total_pages' => '252 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Doodle Art And Typography #1',
                'products_author_name' => 'Gavin`s Story Book',
                'products_publisher_name' => 'Gavin`s Story Book',
                'products_published_year' => '2021',
                'products_price' => '48000',
                'products_stock' => '9',
                'products_summary' => 'Buku yang berjudul Doodle Art And Typography #1 ini merupakan karya dari Gunksmoriart. Buku ini merupakan buku mewarnai yang dapat dinikmati oleh pembaca semua umur. Doodle Art sendiri adalah suatu gaya menggambar dengan cara mencoret, terlihat abstract, ada yang tidak bermakna juga ada yang bermakna, namun terlihat unik dan menarik.',
                'products_isbn' => '9786026731395',
                'products_total_pages' => '30 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Dardanella: Perintis Teater Indonesia Modern, Duta Kesenian Indonesia Melanglang Buana',
                'products_author_name' => 'Jaap Erkelens',
                'products_publisher_name' => 'Penerbit Buku Kompas',
                'products_published_year' => '2022',
                'products_price' => '252000',
                'products_stock' => '3',
                'products_summary' => '“Dardanella”, salah satu rombongan stambul pada dasawarsa pertama setelah Perang Dunia Pertama, tumbuh menjadi rombongan teater paling inovatif. Maka tak berlebihan kalau rombongan ini disebut sebagai perintis teater modern di Indonesia.',
                'products_isbn' => '9786233461979',
                'products_total_pages' => '400 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Art Of Terrarium: Keindahan Taman Dalam Kaca',
                'products_author_name' => 'Feri Sulianta',
                'products_publisher_name' => 'Andi Publisher',
                'products_published_year' => '2019',
                'products_price' => '130000',
                'products_stock' => '3',
                'products_summary' => 'Buku Art Of Terrarium: Keindahan Taman dalam Kaca hadir sebagai panduan pengenalan mengenai kegiatan berterarium di rumah. Buku ini menjelaskan esensi dan informasi dasar yang harus diketahui sebelum berbudidaya ala terarium mulai dari unsur tumbuhan hingga peralatan yang dibutuhkan.',
                'products_isbn' => '9789792906523',
                'products_total_pages' => '124 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => '7 Hari Belajar Drone Photography (Edisi Revisi)',
                'products_author_name' => 'Herry Tjiang',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2024',
                'products_price' => '122000',
                'products_stock' => '8',
                'products_summary' => 'Buku ini dapat dipelajari dalam 7 hari, mempelajari tentang jenis drone, teknik dasar drone, foto dan video, safety prosedur, mapping dan komposisinya. Menjelaskan penggunan software mapping baik untuk menerbangkan dan teknik pemetaan. Menjelaskan komposisi drone yang menarik agar menghasilkan foto yang indah.',
                'products_isbn' => '9789720910220',
                'products_total_pages' => '124 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Drawing Dreams, Start with a Circle',
                'products_author_name' => 'Tri Harianto',
                'products_publisher_name' => 'Tri Harianto',
                'products_published_year' => '2024',
                'products_price' => '130000',
                'products_stock' => '2',
                'products_summary' => 'Drawing Dreams: Start with a Circle" is more than just a drawing book; its a creative adventure. By breaking down complex subjects into simple, circular shapes, this book makes drawing accessible to everyone. Whether youre a child or an adult, youll find joy in bringing these illustrations to life.',
                'products_isbn' => '9787390910284',
                'products_total_pages' => '49 halaman',
                'products_languange' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // BUSINESS
            [
                'products_title' => 'Online to Offline, Offline to Online',
                'products_author_name' => 'Patrick Rimba',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2025',
                'products_price' => '750000',
                'products_stock' => '5',
                'products_summary' => 'Buku ini bukan sekadar panduan biasa. Ini adalah panduan yang dirancang untuk membantu Anda memahami dan menerapkan strategi O2O marketing secara kreatif dan efektif. Dengan strategi ini, bisnis Anda bisa menjangkau lebih banyak pelanggan, meningkatkan daya saing, dan tetap relevan di tengah persaingan yang semakin ketat.',
                'products_isbn' => '9786230069321',
                'products_total_pages' => '136 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Digital Marketing Blueprint',
                'products_author_name' => 'Fatimah Trihani Atuti',
                'products_publisher_name' => 'Anak Hebat Indonesia',
                'products_published_year' => '2025',
                'products_price' => '52000',
                'products_stock' => '9',
                'products_summary' => 'Buku Digital Marketing Blueprint membahas strategi pemasaran digital yang efektif yang dapat digunakan oleh wirausaha untuk meningkatkan visibilitas bisnis mereka di internet. Buku ini membantu pembaca meningkatkan visibilitas daring dan menarik pelanggan potensial dengan panduan praktis dan langkah-langkah mudah.',
                'products_isbn' => '9786235153933',
                'products_total_pages' => '240 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'The Power of Crazy Affiliate',
                'products_author_name' => 'Ken Andaru',
                'products_publisher_name' => 'Diva Press',
                'products_published_year' => '2025',
                'products_price' => '55000',
                'products_stock' => '2',
                'products_summary' => 'Buku ini menjelaskan secara rinci tentang kiat-kiat mudah menjadi afiliator tajir di berbagai platform jualan seperti Shopee, Tokopedia, TikTok, dan lain-lain. Dijelaskan dengan bahasa yang mudah dipahami, buku ini cocok untuk siapa pun yang ingin mendapatkan penghasilan luar biasa dari jalan sebagai afiliator.',
                'products_isbn' => '9786231894175',
                'products_total_pages' => '124 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Etika Bisnis',
                'products_author_name' => 'Bakti Sri Rahayu, S.Pd., SE., MM & Devita Putri Anjarsari S.Kom, MM',
                'products_publisher_name' => 'Pustaka Baru Press',
                'products_published_year' => '2024',
                'products_price' => '44000',
                'products_stock' => '7',
                'products_summary' => 'Adapun tujuan utama penyusunan buku: - bacaan referensi bacaan terhadap mata kuliah Etika; -. untuk memudahkan dan menambah wawasan yang sedang mempelajari maupun mendalami bisnis',
                'products_isbn' => '9786023768479',
                'products_total_pages' => '168 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Mindfulness-Based Business (English Edition)',
                'products_author_name' => 'Sudhamek AWS',
                'products_publisher_name' => 'Gramedia Pustaka Utama',
                'products_published_year' => '2024',
                'products_price' => '200000',
                'products_stock' => '7',
                'products_summary' => 'This book discusses the life journey of Sudhamek in building the Garudafood Group into one of the notable food and beverage companies in modern Indonesian business. He reveals how a business philosophy is developed and used to achieve that goal.',
                'products_isbn' => '9786020677927',
                'products_total_pages' => '252 halaman',
                'products_languange' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Panduan Perdagangan Ekspor Impor',
                'products_author_name' => 'Hasna Wijayati, M.A. & Andika Drajat Murdani, M.A.',
                'products_publisher_name' => 'Anak Hebat Indonesia',
                'products_published_year' => '2025',
                'products_price' => '58000',
                'products_stock' => '7',
                'products_summary' => 'Buku ini adalah panduan lengkap yang menawarkan wawasan menyeluruh mengenai kegiatan ekspor dan impor. Ditulis dengan bahasa yang sederhana dan jelas, buku ini cocok untuk berbagai kalangan, dari pemula hingga profesional sekalipun.',
                'products_isbn' => '9786235154213',
                'products_total_pages' => '242 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Talking to My Daughter About the Economy 2025',
                'products_author_name' => 'Yanis Varoufakis',
                'products_publisher_name' => 'Kepustakaan Populer Gramedia',
                'products_published_year' => '2025',
                'products_price' => '75000',
                'products_stock' => '4',
                'products_summary' => 'Dalam buku ringkas ini, Yanis Varoufakis menjawab pertanyaan anak perempuannya yang begitu sederhana tapi juga begitu menggusarkan itu. Dengan menggunakan analogi dari cerita-cerita klasik maupun populer—dari Oidipus, Frankenstein, hingga The Matrix, ia menjelaskan apa itu ekonomi dan kenapa ekonomi punya daya yang dahsyat dalam membentuk hidup kita.',
                'products_isbn' => '9786024818111',
                'products_total_pages' => '144 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // COMIC
            [
                'products_title' => 'Attack on Titan 24',
                'products_author_name' => 'Elex Media Komputindo',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2018',
                'products_price' => '35000',
                'products_stock' => '7',
                'products_summary' => 'Pada tahun 2009, karya debutnya, yaitu Attack on Titan memulai serialisasi di majalah manga bulanan Bessatsu Shonen Magazine. Manga ini memenangkan kategori Shonen di Penghargaan Manga Kodansha ke-35 pada tahun 2011 dan dinominasikan pada upacara penghargaan tahunan seperti Manga Taish ke-4 dan Penghargaan Budaya Tezuka Osamu ke-16.',
                'products_isbn' => '9786020477114',
                'products_total_pages' => '200 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Blue Lock - Episode Nagi vol. 04',
                'products_author_name' => 'Muneyuki Kaneshiro, Yusuke Nomura',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2025',
                'products_price' => '53000',
                'products_stock' => '7',
                'products_summary' => 'Pada tahun 2009, karya debutnya, yaitu Attack on Titan memulai serialisasi di majalah manga bulanan Bessatsu Shonen Magazine. Manga ini memenangkan kategori Shonen di Penghargaan Manga Kodansha ke-35 pada tahun 2011 dan dinominasikan pada upacara penghargaan tahunan seperti Manga Taish ke-4 dan Penghargaan Budaya Tezuka Osamu ke-16.',
                'products_isbn' => '9786230070631',
                'products_total_pages' => '200 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Hai, Miiko! 35 - Bookpaper',
                'products_author_name' => 'Ono Eriko',
                'products_publisher_name' => 'm&c!',
                'products_published_year' => '2024',
                'products_price' => '50000',
                'products_stock' => '5',
                'products_summary' => 'Tokoh utama komik Hai, Miiko! adalah seorang anak perempuan bernama Miiko Yamada. Dia seorang anak yang periang, setia kawan, dan ramah. Namun, gadis kecil ini tidak digambar dengan sifat yang sempurna. Tipikal anak-anak SD, Miiko sangat suka bermain dan sebagainya, namun tidak begitu tertarik dengan hal sepert beres-beres ataupun belajar.',
                'products_isbn' => '9786230314094',
                'products_total_pages' => '112 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Dandadan 03',
                'products_author_name' => 'Tatsu Yukinobu',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2025',
                'products_price' => '45000',
                'products_stock' => '3',
                'products_summary' => 'Okarun dan Momo sedang mencari biji yang berharga bagi pria, yang hilang ketika melawan nenek-turbo. Sementara itu, Aira, seorang gadis cantik yang kekuatan spiritualnya bangkit karena memungut biji tersebut, memanggil Momo karena salah mengira Momo si pemilik kekuatan gaib sebagai iblis. Tetapi, di lokasi muncul Rambut-Sutra Akrobatik, si wanita bergaun merah, dan menyerang mereka berdua!?',
                'products_isbn' => '9786230069710',
                'products_total_pages' => '210 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Hai, Miiko 18 - Bookpaper',
                'products_author_name' => 'Eriko Ono',
                'products_publisher_name' => 'm&c!',
                'products_published_year' => '2025',
                'products_price' => '49000',
                'products_stock' => '6',
                'products_summary' => '"Ayo pilih jari Miiko! Mau ibu jari, telunjuk, jari tengah, jari manis atau kelingking? Semuanya mewakili perasaanmu, lho!"',
                'products_isbn' => '9786230316722',
                'products_total_pages' => '192 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Friendzone Vol.1',
                'products_author_name' => 'Vanesa Marcella',
                'products_publisher_name' => 'Bentang Pustaka',
                'products_published_year' => '2019',
                'products_price' => '52500',
                'products_stock' => '4',
                'products_summary' => 'Di mata Abel, David adalah cowok sempurna. Dia ganteng, populer, meski tengil tetapi baik, dan selalu berada di sisi Abel. Tiap David memandangnya, Abel selalu berharap rona merah di pipinya tidak ketahuan oleh David. Apalagi saat David menyentuhnya, mengacak rambutnya, seolah seluruh partikel di dalam tubuh Abel siap melesat tinggi menembus langit.',
                'products_isbn' => '9786024303921',
                'products_total_pages' => '151 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Yotsuba &! 15',
                'products_author_name' => 'Kiyohiko Azuma',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2023',
                'products_price' => '45000',
                'products_stock' => '7',
                'products_summary' => 'Yotsuba, Ena, Miura, dan ayah pergi ke pantai untuk mencari batu. Karena harus mencari batu yang sesuai dengan keinginan Yotsuba, mereka pun harus pergi naik mobil sampai ke kota sebelah. Apakah petualangan mereka kali ini akan berhasil? Batu seperti apa yang akan ditemukan Yotsuba?',
                'products_isbn' => '9786230045738',
                'products_total_pages' => '264 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // HISTORY
            [
                'products_title' => 'Arsitektur Rumah Jawa : Mengungkap Filosofi Makna dan Simbologinya',
                'products_author_name' => 'Asti Musman',
                'products_publisher_name' => 'Anak Hebat Indonesia',
                'products_published_year' => '2024',
                'products_price' => '59000',
                'products_stock' => '1',
                'products_summary' => 'Penting bagi generasi sekarang, baik bagi mereka yang secara langsung mewarisi nilai-nilai ini maupun bagi siapapun yang menghargai kebudayaan dan nilai-nilai mulianya, untuk memahami dan menghargai filosofi ini. Bagaimanapun, pemahaman ini menjadi kunci untuk menjaga keberlangsungan budaya di tengah arus modernisasi yang semakin menguat.',
                'products_isbn' => '9786231648303',
                'products_total_pages' => '230 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Filosofi Rumah Tradisional Jawa',
                'products_author_name' => 'Asti Musman',
                'products_publisher_name' => 'Anak Hebat Indonesia',
                'products_published_year' => '2022',
                'products_price' => '78000',
                'products_stock' => '3',
                'products_summary' => 'Banyak penggambaran sosok orang Jawa yaitu orang yang sederhana, tidak memikirkan kenyamanan dalam kehidupannya. Urip mung mampir ngombe (hidup hanya untuk mampir minum) dalam arti hidup hanya sesaat di dunia, sehingga seolah-olah orang Jawa tidak peduli dengan kebendaan dan segala yang menjadi kesukaan duniawi. Anggapan itu ternyata keliru, seorang lelaki Jawa dianggap sempurna hidupnya jika sudah memiliki 5 syarat yaitu wisma (rumah), turangga (kuda), kukila (burung), wanodya (wanita) dan curiga (keris).',
                'products_isbn' => '9786234003109',
                'products_total_pages' => '230 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Petualangan Marco Polo',
                'products_author_name' => 'Marco Polo',
                'products_publisher_name' => 'Alvabet',
                'products_published_year' => '2025',
                'products_price' => '145000',
                'products_stock' => '8',
                'products_summary' => 'Berisi kisah petualangan Marco Polo—penjelajah paling masyhur pada masanya—yang memulai pelayarannya pada 1271 dengan kunjungan ke Tiongkok, setelah itu ia melayani Kubilai Khan dalam berbagai misi diplomatik ke banyak negeri. Dan, setelah 24 tahun merantau, sekembalinya ke negerinya, ia menceritakan semua yang telah dialaminya kepada Rustichello, yang mencatat semua peristiwa unik dan seru selama perjalanannya, dan jadilah buku yang sedang Anda pegang ini. Salah satu buku perjalanan besar pertama dalam sastra Barat.',
                'products_isbn' => '9786232201972',
                'products_total_pages' => '230 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Merawat Kehidupan – 100 Tahun Rumah Sakit Husada (Jang Seng Ie)',
                'products_author_name' => 'Perkumpulan Husada',
                'products_publisher_name' => 'Penerbit Buku Kompas',
                'products_published_year' => '2025',
                'products_price' => '145000',
                'products_stock' => '2',
                'products_summary' => 'Selama satu abad, RS Husada—sebelumnya bernama Jang Seng Ie (JSI)—telah menjadi simbol pengabdian masyarakat Tionghoa dalam dunia kesehatan di Indonesia. Didirikan pada 28 Desember 1924 atas prakarsa dr. Kwa Tjoan Sioe, kehadiran JSI mampu mendobrak sistem kesehatan kolonial yang sering kali tidak berpihak pada masyarakat miskin. Buku ini mengisahkan perjalanan JSI hingga menjadi RS Husada dan perjuangannya dalam mewujudkan akses kesehatan yang inklusif dan merata bagi seluruh lapisan masyarakat.',
                'products_isbn' => '9786235233765',
                'products_total_pages' => '424 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Little People Big Dreams: Maria Montessori',
                'products_author_name' => 'Maria Isabel Sanchez Vegara Little People Big ',
                'products_publisher_name' => 'Kepustakaan Populer Gramedia',
                'products_published_year' => '2025',
                'products_price' => '108000',
                'products_stock' => '3',
                'products_summary' => 'Ungkap kehidupan tokoh-tokoh terkemuka di berbagai bidang. Semua menghasilkan karya luar biasa dan mereka memulainya sebagai anak-anak dengan mimpi besar! Sejak muda, Maria Montessori sudah mendobrak kebiasaan yang ada dengan belajar sains di sekolah khusus putra. Setelah dewasa, ia menjadi dokter perempuan pertama yang berfokus pada kesejahteraan anak-anak.',
                'products_isbn' => '9786231342942',
                'products_total_pages' => '32 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ //novel ini
                'products_title' => 'Little Women (Republish 2025)',
                'products_author_name' => 'Louisa May Alcott',
                'products_publisher_name' => 'Mizan',
                'products_published_year' => '2025',
                'products_price' => '108000',
                'products_stock' => '7',
                'products_summary' => 'Karya klasik yang tak lekang oleh waktu ini bercerita tentang kehidupan empat bersaudari, suatu masa di Concord, Massachusetts. Meg, si Cantik keibuan yang bermimpi menjadi ratu bergaun indah. Jo, si Tomboi yang sangat mencintai buku dan sastra. Beth, si Pendiam yang begitu berbakat memainkan piano. Dan Amy, Michelangelo kecil dengan sketsa-sketsa memukau di kertas gambarnya.',
                'products_isbn' => '9786024413798',
                'products_total_pages' => '444 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ //novel ini
                'products_title' => 'Shogun Jilid 2',
                'products_author_name' => 'James Clavell',
                'products_publisher_name' => 'Kepustakaan Populer Gramedia',
                'products_published_year' => '2025',
                'products_price' => '145000',
                'products_stock' => '8',
                'products_summary' => 'Setelah terdampar di Jepang, nakhoda Inggris John Blackthorne terus berusaha memahami negeri asing itu selagi dia jadi terlibat dalam rencana besar Yoshi Toranaga untuk berjaya dalam pertarungan antarkubu samurai. Berada di tempat di mana perkara kehormatan bisa menentukan antara hidup dan mati, Blackthorne harus mengandalkan bimbingan Mariko dalam menghadapi berbagai petualangan dan pengkhianatan.',
                'products_isbn' => '9786231343284',
                'products_total_pages' => '472 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // COMEDY
            [
                'products_title' => 'Koleksi Humor Gus Dur Paling Nyeleneh',
                'products_author_name' => 'Guntur Wiguna',
                'products_publisher_name' => 'Narasi',
                'products_published_year' => '2018',
                'products_price' => '45000',
                'products_stock' => '7',
                'products_summary' => '“Koleksi Humor Gus Dur Paling Nyeleneh” merupakan buku bergenre komedi karya Guntur Wiguna. K.H. Abdurrahman Wahid atau biasa disapa Gus Dur merupakan sosok fenomenal dan sangat istimewa. Meski telah tiada, tetapi ide serta pemikiran-pemikirannya seolah tak lekang oleh waktu dan kisah hidupnya masih terus menjadi pembahasan yang menarik.',
                'products_isbn' => '9789791685283',
                'products_total_pages' => '164 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Prisma: Humor Yang Adil & Beradab',
                'products_author_name' => 'LP3ES',
                'products_publisher_name' => 'Narasi',
                'products_published_year' => '2019',
                'products_price' => '120500',
                'products_stock' => '7',
                'products_summary' => 'Dalam volume kali ini menghadirkan pembahasan secara rinci dan variatif mengenai penggunaan humor dalam pelengkap dan metode pewarna politik di dalam suatu negara. Jurnal dilengkapi dengan tulisan jurnal "topik kita", kumpulan esai, dan termasuk analisa Seno Gumira Ajidarma mengenai ruang lingkup humor.',
                'products_isbn' => '208011725',
                'products_total_pages' => '- halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Jomblo: sebuah komedi cinta',
                'products_author_name' => 'Adhitya Mulya',
                'products_publisher_name' => 'GagasMedia',
                'products_published_year' => '2003',
                'products_price' => '230000',
                'products_stock' => '3',
                'products_summary' => 'Empat sahabat dengan masalah mereka dalam mencari cinta. Yang satu harus memilih—seorang yang baik atau yang cocok. Yang satu harus memilih—antara seorang perempuan atau sahabat. Yang satu harus memilih—lebih baik diam saja selamanya atau menyatakan cinta. Yang satu harus memilih—terus mencoba atau tidak sama sekali.',
                'products_isbn' => '384011857',
                'products_total_pages' => '175 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'My Youth Romantic Comedy Is Wrong As I Expected @Comic 5',
                'products_author_name' => 'Wataru Watari, Naomichi Io, Ponkan8',
                'products_publisher_name' => 'Elex Media Komputindo',
                'products_published_year' => '2021',
                'products_price' => '310000',
                'products_stock' => '3',
                'products_summary' => 'My Teen Romantic Comedy SNAFU, adalah seri komik ringan Jepang yang ditulis oleh Wataru Watari dan diilustrasikan oleh Ponkan8. Serial ini mengikuti Hachiman Hikigaya, seorang remaja pesimis, tertutup, dan realistis, yang dipaksa oleh gurunya untuk bergabung dengan klub layanan sekolah dan bekerja dengan dua gadis dengan masalah mereka sendiri. Mereka menawarkan bantuan dan saran kepada orang lain saat menghadapi konflik batin mereka.',
                'products_isbn' => '9786230019821',
                'products_total_pages' => '184 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Hyperbole and a Half',
                'products_author_name' => 'Allie Brosh',
                'products_publisher_name' => 'First Edition',
                'products_published_year' => '2013',
                'products_price' => '250000',
                'products_stock' => '4',
                'products_summary' => '"Hyperbole and a Half" is a darkly humorous and poignant graphic memoir by Allie Brosh, exploring her life experiences through a mix of exaggerated storytelling and relatable, often flawed, coping mechanisms. The book blends humor with deep dives into Broshs struggles with depression, offering insights into the struggles of navigating mental health and everyday life.',
                'products_isbn' => '9382206219061',
                'products_total_pages' => '369 halaman',
                'products_languange' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Ubur-Ubur Lembur',
                'products_author_name' => 'Raditya Dika',
                'products_publisher_name' => 'Gagas Media',
                'products_published_year' => '2018',
                'products_price' => '69000',
                'products_stock' => '9',
                'products_summary' => 'Ubur-ubur Lembur adalah buku komedi Raditya Dika. Bercerita tentang pengalamannya belajar hidup dari apa yang dia cintai, sambil menemukan hal remeh untuk ditertawakan di sepanjang perjalanan. Seluruh bab di dalamnya diangkat dari kisah nyata.',
                'products_isbn' => '9280276861984',
                'products_total_pages' => '232 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'SkripSick: Derita Mahasiswa Abadi',
                'products_author_name' => 'Chara Perdana',
                'products_publisher_name' => 'Matahari',
                'products_published_year' => '2014',
                'products_price' => '69000',
                'products_stock' => '9',
                'products_summary' => 'Novel ini begitu dekat dengan realita kehidupan mahasiswa, sehingga banyak yang merasa terwakili dengan cerita-cerita yang disajikan. Melalui gaya penulisan yang ringan dan humor yang khas, Chara mengajak pembaca untuk menyelami lika-liku proses pengerjaan skripsi, mulai dari pemilihan judul hingga perjuangan menghadapi dosen pembimbing. ',
                'products_isbn' => '9764270751903',
                'products_total_pages' => '232 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // NOVEL
            [
                'products_title' => 'Hati yang Berani, Sahabat Sejati',
                'products_author_name' => 'Immanuela D. Nindhita',
                'products_publisher_name' => 'Penerbit Buku Kompas',
                'products_published_year' => '2023',
                'products_price' => '67000',
                'products_stock' => '7',
                'products_summary' => 'Haris, seorang remaja yang hidupnya tampak bahagia dari luar, karena keluarganya kaya dan ia memiliki paras yang menarik. Namun, pada kenyataannya, Haris merasa kesepian dan tidak bahagia karena keluarganya jarang berkumpul dan kurang memberikan kasih sayang',
                'products_isbn' => '9786231601544',
                'products_total_pages' => '104 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Nikola Maldini',
                'products_author_name' => 'Kale',
                'products_publisher_name' => 'Cloud Books',
                'products_published_year' => '2023',
                'products_price' => '100000',
                'products_stock' => '5',
                'products_summary' => 'Nikola Pramudya Sadeli, si ribut sekaligus juga si pekerja keras yang selalu dihantui oleh mimpi-mimpi buruk akibat kelalaiannya di masa lalu. Pikirannya selalu riuh dengan berbagai hal karena dia adalah tipikal manusia yang sulit untuk dipahami.',
                'products_isbn' => '9786235266367',
                'products_total_pages' => '348 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Anne of Avonlea',
                'products_author_name' => 'Lucy M. Montgomery',
                'products_publisher_name' => 'Mizan Publishing',
                'products_published_year' => '2023',
                'products_price' => '93000',
                'products_stock' => '3',
                'products_summary' => 'Kita semua pernah membuat kesalahan. Kita harus menyesali kesalahan kita dan belajar dari situ, tapi jangan pernah terus membawa kesalahan itu ke masa depan. Itulah yang dikisahkan dalam Anne of Avonlea.',
                'products_isbn' => '9786024413118',
                'products_total_pages' => '432 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'The Psychology of Money Edisi Revisi',
                'products_author_name' => 'Morgan Housel',
                'products_publisher_name' => 'Baca',
                'products_published_year' => '2024',
                'products_price' => '82000',
                'products_stock' => '9',
                'products_summary' => 'Dalam The Psychology of Money, penulis pemenang penghargaan, Morgan Housel membagikan 19 cerita pendek yang mengeksplorasi cara-cara aneh orang berpikir tentang uang dan mengajari Anda cara memahami salah satu topik terpenting dalam hidup dengan lebih baik.',
                'products_isbn' => '9786238371044',
                'products_total_pages' => '294 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Positivity Power',
                'products_author_name' => 'R.D. Asti',
                'products_publisher_name' => 'Metamedia Pustaka',
                'products_published_year' => '2025',
                'products_price' => '65000',
                'products_stock' => '9',
                'products_summary' => 'Positivity Power: Rahasia Keajaiban Kekuatan Pikiran. Pikiran lebih dari sekadar hasil dari kegiatan berpikir. Pikiran adalah hal yang menuntun kita dalam menjalani hidup dan mendefinisikan diri kita. Pikiran membentuk pandangan kita terhadap dunia dan orang-orang disekitar kita.',
                'products_isbn' => '9786231056375',
                'products_total_pages' => '200 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'The Magic of Luck',
                'products_author_name' => 'Mugi Rudhi Tata',
                'products_publisher_name' => 'Araska Publisher',
                'products_published_year' => '2025',
                'products_price' => '73000',
                'products_stock' => '5',
                'products_summary' => 'The Magic of Luck: Rahasia Menciptakan Keberuntungan di Segala Situasi. Keberuntungan bukan semata-mata kebetulan, melainkan hasil dari usaha, mindset positif, dan langkah-langkah nyata yang kita ambil setiap hari. Seperti kata Seneca, "Keberuntungan adalah ketika persiapan bertemu dengan peluang atau kesempatan."',
                'products_isbn' => '9786236335796',
                'products_total_pages' => '180 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Berpikir dan Bertindak Besar',
                'products_author_name' => 'Dewi Indra Puspitasari',
                'products_publisher_name' => 'Anak Hebat Indonesia',
                'products_published_year' => '2024',
                'products_price' => '57000',
                'products_stock' => '3',
                'products_summary' => '“Berpikir besar” berarti mampu memimpikan dan memvisualisasikan apa yang dapat Anda capai dengan keberanian dan tanpa batas. Ini adalah tentang berpikiran terbuka, positif, kreatif, dan melihat peluang dalam gambaran besar. Banyak orang terpikat oleh ide-ide besar, tetapi sangat sulit untuk mewujudkannya. Mengapa? Karena mereka cenderung membiarkan pikiran mereka berjalan bebas dan liar.',
                'products_isbn' => '9786235151311',
                'products_total_pages' => '246 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'products_title' => 'Harry Potter and the Sorcerers Stone',
                'products_author_name' => 'J.K. Rowling',
                'products_publisher_name' => 'Bloomsbury',
                'products_published_year' => '1997',
                'products_price' => '150000',
                'products_stock' => '50',
                'products_summary' => 'Petualangan pertama Harry Potter di Hogwarts. Harry Potter and the Sorcerers Stone berkisah tentang kehidupan penyihir muda bernama Harry Potter. Film ini juga berfokus pada konflik antara Harry dengan penyihir jahat bernama Voldemort yang telah membunuh kedua orang tuanya.',
                'products_isbn' => '9621392182902',
                'products_total_pages' => '336 halaman',
                'products_languange' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
